name: Enable Auto Merge

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Approve a PR
        run: |
          gh pr review "${{ github.event.pull_request.number }}" --approve --body "Auto-approved by GitHub Actions."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Enable auto-merge
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
