name: Build on PR

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'yarn'
      
    - name: Install dependencies
      run: yarn install
      
    - name: Lint
      run: yarn lint
      
    - name: Build
      run: yarn build
